/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantautomation;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.ResturantConnection;
import operations.*;
/**
 *
 * @author Alejandro
 */
public class Login_GUI extends javax.swing.JFrame {

    boolean login = false;
    ResturantConnection rd = new ResturantConnection ();
    /**
     * Creates new form Login_GUI
     */
    public Login_GUI() {
        
        initComponents();
        invalidText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        unTextField = new javax.swing.JTextField();
        pwTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        invalidText = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        unTextField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        unTextField.setForeground(new java.awt.Color(153, 153, 153));
        unTextField.setText("Username");
        unTextField.setBorder(null);
        unTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        unTextField.setMargin(new java.awt.Insets(2, 5, 2, 2));
        unTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearUsernameText(evt);
            }
        });
        unTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unTextFieldActionPerformed(evt);
            }
        });

        pwTextField.setForeground(new java.awt.Color(153, 153, 153));
        pwTextField.setText("Password");
        pwTextField.setBorder(null);
        pwTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearPasswordText(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        invalidText.setForeground(new java.awt.Color(255, 102, 102));
        invalidText.setText("Invalid login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(invalidText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(pwTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loginText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        loginText.setForeground(new java.awt.Color(153, 153, 153));
        loginText.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginText)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(loginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String user_id =  unTextField.getText();
        String password =  pwTextField.getText();
        
        int emp_id=Integer.parseInt(user_id);
        EmployeeOperations employee= new EmployeeOperations(); 
        
//        System.out.println(rd.getEmployeeData("Sen"));
//        System.out.println(rd.getEmployeeData("Homer"));
//        System.out.println(rd.getEmployeeData("Peter"));
        try {
            // Checks is username is in database
            if (employee.isEmployee(emp_id)) {
                // Chaecks if the password of the database is related to the username
                if (password.equals(employee.getEmployeeByID(emp_id).getPassword())){
                    
                    this.login = true;
                    
                    invalidText.setVisible(false);
                    
                   
                    //If login is for waiter...
                    
                    System.out.println("Waiter Login");
                    Table_Gui rL = new Table_Gui (employee.getEmployeeByID(emp_id));
                    rL.setVisible(true);
                    
                    
                } else {
                    invalidText.setText("Invalid Username - Password combination");
                    invalidText.setVisible(true);
                }
                //setVisible(false);
                
            } else {
                invalidText.setText("Username not found");
                invalidText.setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void ClearUsernameText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearUsernameText
        // TODO add your handling code here:
        if (unTextField.getText().equals("Username")) {
            unTextField.setText("");
        }
        
        if (pwTextField.getText().equals("")) {
            pwTextField.setText("Password");
        }
    }//GEN-LAST:event_ClearUsernameText

    private void clearPasswordText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearPasswordText
        // TODO add your handling code here:
        if (pwTextField.getText().equals("Password")) {
            pwTextField.setText("");
        }
        
        if (unTextField.getText().equals("")) {
            unTextField.setText("Username");
        }
    }//GEN-LAST:event_clearPasswordText

    private void unTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unTextFieldActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invalidText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginText;
    private javax.swing.JPasswordField pwTextField;
    private javax.swing.JTextField unTextField;
    // End of variables declaration//GEN-END:variables
}
